// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Message struct {
	ID       int64     `json:"id"`
	Group    string    `json:"group"`
	Message  string    `json:"message"`
	SentAt   time.Time `json:"sent_at"`
	Read     bool      `json:"read"`
	SentFrom int64     `json:"sent_from"`
	SentTo   int64     `json:"sent_to"`
}

type MessageGroup struct {
	ID         int64  `json:"id"`
	Identifier string `json:"identifier"`
	FromUser   int64  `json:"from_user"`
	ToUser     int64  `json:"to_user"`
}

type Users struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}
