// Code generated by sqlc. DO NOT EDIT.
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: createUser :one
INSERT INTO "users"(
    username
) VALUES (
    $1
) RETURNING id, username, created_at
`

func (q *Queries) createUser(ctx context.Context, username string) (Users, error) {
	row := q.db.QueryRowContext(ctx, createUser, username)
	var i Users
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return i, err
}
